# Generated by Django 2.1.1 on 2018-09-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratovuelo',
            name='vuelo',
        ),
        migrations.AddField(
            model_name='contratovuelo',
            name='vuelo',
            field=models.ManyToManyField(to='home.Vuelo'),
        ),
    ]
