# Generated by Django 2.1.1 on 2018-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180918_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='imageplan',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='home.ImagePlan'),
        ),
    ]
