# Generated by Django 2.1.1 on 2018-09-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180918_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratovuelo',
            name='vuelo',
            field=models.ManyToManyField(to='home.Vuelo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='imageplan',
            field=models.ManyToManyField(blank=True, null=True, to='home.ImagePlan'),
        ),
    ]
