# Generated by Django 2.1.1 on 2018-09-18 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180918_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='turista',
            name='pasaporte',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='turista',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Comprador'),
        ),
    ]
